
name = "DashShadcn"
uuid = "1b08a953-4be3-4667-9a23-96af5fe1e4d1"
authors = ["Guillaume Thibault <guillaume.thibault.98@proton.me>"]
version = "0.0.1"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3, 1.0"
